export:
  enabled_targets:
    - notion
    - sheets
    - s3://your-bucket/exports/

  filters:
    min_priority: Medium
    allowed_tags: [marketing, finance, hr]
    exclude_assigned_to: [Temporary Intern]

aws:
  region: your-aws-region
  access_key_id: your-access-key-id
  secret_access_key: your-secret-access-key
