export:
  enabled_targets:
    - notion
    - sheets
    - s3://my-ghost-employee-exports/exports/

  filters:
    min_priority: Medium
    allowed_tags: [marketing, finance, hr]
    exclude_assigned_to: [Temporary Intern]
    